<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Reactive" Version="6.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DisplayUtil.Building\DisplayUtil.Building.csproj"/>
        <ProjectReference Include="..\DisplayUtil.Infrastructure\DisplayUtil.Infrastructure.csproj"/>
        <ProjectReference Include="..\DisplayUtil.Layouting\DisplayUtil.Layouting.csproj"/>
    </ItemGroup>

</Project>
